name: Build and Package Go Application for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o YOUR_EXECUTABLE_FILE.exe -v

    - name: Package
      run: |
        mkdir -p build
        cp YOUR_EXECUTABLE_FILE.exe build/
        zip -r release.zip build/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip
